const express = require('express');
const router = express.Router();
const axios = require('axios');
const cors = require('cors');

const { GoogleGenerativeAI } = require("@google/generative-ai");

router.use(cors({
    origin: 'https://smpfe.netlify.app', // Replace with your frontend URL
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"], // Include DELETE
    allowedHeaders: ["Content-Type", "Authorization"], // Include any necessary headers

    credentials: true
}));

const API_KEY = 'AIzaSyCjp4hY8BiN_rdcWQ6NHfFoMILhdysLcB0'; // Secure your API key in environment variables
if (!API_KEY) {
    console.error("API key is missing. Please set GOOGLE_GEN_AI_API_KEY in your environment variables.");
    process.exit(1);
}

const genAI = new GoogleGenerativeAI(API_KEY);

// Endpoint to generate captions
router.post("/generate-captions", async (req, res) => {
    const { topic } = req.body;

    // Validate request payload
    if (!topic || typeof topic !== "string") {
        return res.status(400).json({ error: "Invalid or missing 'topic'. Please provide a valid string." });
    }

    const numberOfCaptions = 5; // Default number of captions
    const prompt = `Generate ${numberOfCaptions} creative and professional captions for social media posts about '${topic}'. Each caption should include 5 relevant and trending hashtags.`;

    try {
        const model = genAI.getGenerativeModel({ model: "gemini-pro" });
        const result = await model.generateContent({
            prompt,
            maxOutputTokens: 200, // Limit response length
            temperature: 0.7, // Control randomness for more engaging results
        });

        // Process the result and extract captions
        const captions = result.candidates.map((candidate) => candidate.content);

        if (!captions || captions.length === 0) {
            throw new Error("No captions generated by the model.");
        }

        // Return the generated captions
        res.json({ captions });
    } catch (err) {
        console.error("Error generating captions:", err.message || err);
        res.status(500).json({ error: "Failed to generate captions. Please try again later." });
    }
});



module.exports = router;






